[tool.poetry]
name = "pymusiclooper"
version = "4.0.0"
description = "Create seamless music loops with video generation capabilities"
license = "MIT"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Multimedia :: Sound/Audio :: Analysis",
    "Topic :: Multimedia :: Video",
]
readme = "README.md"
authors = ["arkrow <arkrow@protonmail.com>", "taylor"]

[tool.poetry.dependencies]
python = "^3.8"
librosa = "^0.10.0"
numpy = ">=1.24.0"
soundfile = ">=0.12.1"
sounddevice = ">=0.4.6"
rich = ">= 13.4.2"
pytaglib = ">=2.0.0"
numba = "^0.57.0"
yt-dlp = ">=2023.11.16"
lazy-loader = ">=0.3"
pillow = "^10.2.0"
moviepy = "^1.0.3"
ffmpeg-python = "^0.2.0"
imageio = "^2.33.1"
glitch-this = "^1.0.2"
randimage = "^1.2"
pydub = "*"

[tool.poetry.scripts]
pymusiclooper = "pymusiclooper.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ['py38']

[tool.isort]
profile = "black"

[tool.ruff]
ignore = ["E501", "E402"]
